title: "مدونة الخوارزميات"
locale: ar
author: gom3a
description: "مقالات لشرح مسائل خوارزميات ومسابقات برمجة"
theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM
